### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by christopherpickering** [moy2010/meilisearch-github-action#10]
Hi! I get a docker error when using this - 
`docker: invalid reference format: repository name must be lowercase.`

I'm thinking because my repository name has a hyphen in it, but I'm not sure... the repo name is lowercase "this-repo".

**Comment by moy2010** [comment]
Check that you have provided a valid `meilisearch-version` as per the examples in the Readme file.

**Comment by christopherpickering** [comment]
Thanks! I tried w/ latest and v0.30.5. Here's an example:

```yaml
name: Test

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - name: Start Meilisearch
    #   run: |
    #     docker run -d --rm --name meilisearch -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v0.30
    - name: Start Meilisearch
      uses: moy2010/meilisearch-github-action@0.1
      with:
        meilisearch-version: v0.30.5

    - name: check search
      run: sleep 5; curl -v http://localhost:7700/health
```

I tried also v0.30.

Here's the github output:

```yaml
Run moy2010/meilisearch-github-action@0.1
[2](#step:6:2)
  with:
[3](#step:6:3)
    meilisearch-version: v0.30
[4](#step:6:4)
    meilisearch-port: 7700
[5](#step:6:5)
    meilisearch-api-key: meilisearch
[6](#step:6:7)
/usr/bin/docker run --name f34d147b6c43ee882da06b12ddd1a2_66cb62 --label 290506 --workdir /github/workspace --rm -e "INPUT_MEILISEARCH-VERSION" -e "INPUT_MEILISEARCH-PORT" -e "INPUT_MEILISEARCH-API-KEY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --network github_network_5d84e01c7166464e931a9c3e3a43bcec -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/prayer-calendar/prayer-calendar":"/github/workspace" 290506:73f34d147b6c43ee882da06b12ddd1a2  "v0.30" "7700" "meilisearch"
[7](#step:6:8)
Starting Meilisearch server
[8](#step:6:9)
    - port [7700]
[9](#step:6:10)
    - version [v0.30]
[10](#step:6:11)
    - api key [meilisearch]
[11](#step:6:12)
  
[12](#step:6:13)
  docker: invalid reference format: repository name must be lowercase.

```
