### ISSUE TITLE
Add support for Mac and Windows

### ISSUE THREAD

**Issue by waybackarchiver** [moy2010/meilisearch-github-action#9]
Hello everyone,

Currently, container action is only supported on Linux; is there any plan to add support for Mac and Windows?

**Comment by waybackarchiver** [comment]
We created an [alternative action](https://github.com/wabarc/.github/tree/0c62d131c3884390bd63a2b7650a21fe16581bfe/meilisearch), you can file the step to use it!

```yaml
steps:
  - name: Set up Meilisearch
    uses: wabarc/.github/meilisearch@main
```

cc @Kerollmops @curquiza
